### ISSUE TITLE
Integratino with write-good?

### ISSUE THREAD

**Issue by alehandrof** [duereg/sublime-write-gooder#1]
`write-gooder` is listed as deprecated on npm and the suggestion is to use `write-good`. Is there a plan to revise this plugin accordingly?

**Comment by duereg** [comment]
No, because the formatting that write-gooder uses is totally different than write-good. This plugin also has a plugin that write-good doesn't. 

Also, I'm a contributor to write-good, so these two won't ever get that out of sync.

**Comment by alehandrof** [comment]
Thanks for getting back to me. I'm a little confused about the two Sublime plugins that provide write-good-ish behavior. But I'll go bark up their tree :)

**Comment by duereg** [comment]
oh, there is another plugin? I didn't know

**Comment by alehandrof** [comment]
Yes, there's a [write-good plugin](https://github.com/ckaznocha/SublimeLinter-contrib-write-good) for SublimeLinter. It makes sense to rely on SL's framework. Unfortunately, as I [it only works for comments](https://github.com/ckaznocha/SublimeLinter-contrib-write-good/issues/2) because it's designed for coders not writers.
